# Generated by Django 4.2.7 on 2023-11-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('image', models.ImageField(default='comp.jpg', upload_to='')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
