# Generated by Django 4.2.7 on 2023-11-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=300)),
                ('intro', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('img', models.ImageField(default='quiz.jpg', upload_to='')),
            ],
        ),
    ]
