# Generated by Django 4.2.7 on 2023-11-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('detail', models.TextField()),
                ('poster', models.ImageField(default='soon.jpeg', upload_to='')),
            ],
        ),
    ]
