# Generated by Django 4.2.7 on 2023-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.CharField(default='https://wwww', max_length=300),
        ),
    ]
