# Generated by Django 4.2.7 on 2023-11-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_event_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('star', models.IntegerField()),
                ('img', models.ImageField(default='icon.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='comments',
            field=models.IntegerField(default=56),
        ),
        migrations.AddField(
            model_name='courses',
            name='users',
            field=models.IntegerField(default=175),
        ),
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.CharField(default='https://www.wikipedia.com', max_length=300),
        ),
    ]
