# Generated by Django 4.2.7 on 2023-12-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0007_review_courses_comments_courses_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img1', models.ImageField(default='write.jpg', upload_to='')),
                ('img2', models.ImageField(default='write.jpg', upload_to='')),
                ('img3', models.ImageField(default='write.jpg', upload_to='')),
            ],
        ),
    ]
